In [1]:
#4.3.1 通过数组观察转换效果
#将RGB转换成灰度图像
import cv2
import numpy as np
img=np.random.randint(0,256,[2,4,3],dtype=np.uint8)
rst=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
print("img=\n",img)
print("rst=\n",rst)
print("像素点(1,0)直接计算得到的值=",img[1,0,0]*0.114+img[1,0,1]*0.587+img[1,0,2]*0.299)
print("像素点(1,0)使用公式cv2.cvtColor()转换值=",rst[1,0])

img=
 [[[136   1 184]
  [131 177 131]
  [ 65  42 191]
  [170  10  90]]

 [[ 80 190 251]
  [187 142 126]
  [206  34  56]
  [190 209  40]]]
rst=
 [[ 71 158  89  52]
 [196 142  60 156]]
像素点(1,0)直接计算得到的值= 195.69899999999998
像素点(1,0)使用公式cv2.cvtColor()转换值= 196


In [2]:
import cv2
import numpy as np
img=np.random.randint(0,256,[2,4],dtype=np.uint8)
rst=cv2.cvtColor(img,cv2.COLOR_GRAY2RGB)
print("img=\n",img)
print("rst=\n",rst)

img=
 [[153 142 229  86]
 [ 49 120  94 154]]
rst=
 [[[153 153 153]
  [142 142 142]
  [229 229 229]
  [ 86  86  86]]

 [[ 49  49  49]
  [120 120 120]
  [ 94  94  94]
  [154 154 154]]]


In [3]:
#4.3.2 图像处理实例
import cv2
lena=cv2.imread("lena.png",-1)
gray=cv2.cvtColor(lena,cv2.COLOR_BGR2GRAY)
rgb=cv2.cvtColor(lena,cv2.COLOR_BGR2RGB)
#===============打印shape========================###
print("lena.shape=",lena.shape)
print("gray.shape=",gray.shape)
print("rgb.shape=",rgb.shape)
#================显示效果========================###
cv2.imshow("lena",lena)
cv2.imshow("gray",gray)
cv2.imshow("rgb",rgb)
cv2.waitKey()
cv2.destroyAllWindows()

lena.shape= (300, 300, 3)
gray.shape= (300, 300)
rgb.shape= (300, 300, 3)


In [4]:
#4.4 HSV色彩空间
#4.4.2 获取指定颜色
import cv2
import numpy as np
#========测试一下OpenCV中蓝色的HSV模式值========###
imgBlue=np.zeros([1,1,3],dtype=np.uint8)
imgBlue[0,0,0]=255
Blue=imgBlue
BlueHSV=cv2.cvtColor(Blue,cv2.COLOR_BGR2HSV)
print("Blue=\n",Blue)
print("BlueHSV",BlueHSV)
#========测试一下OpenCV中绿色的HSV模式值========###
imgGreen=np.zeros([1,1,3],dtype=np.uint8)
imgGreen[0,0,1]=255
Green=imgGreen
GreenHSV=cv2.cvtColor(Green,cv2.COLOR_BGR2HSV)
print("Green=\n",Green)
print("GreenHSV",GreenHSV)
#========测试一下OpenCV中红色的HSV模式值========###
imgRed=np.zeros([1,1,3],dtype=np.uint8)
imgRed[0,0,2]=255
Red=imgRed
RedHSV=cv2.cvtColor(Red,cv2.COLOR_BGR2HSV)
print("Red=\n",Red)
print("RedHSV",RedHSV)

Blue=
 [[[255   0   0]]]
BlueHSV [[[120 255 255]]]
Green=
 [[[  0 255   0]]]
GreenHSV [[[ 60 255 255]]]
Red=
 [[[  0   0 255]]]
RedHSV [[[  0 255 255]]]


In [5]:
#4.4.3 标记指定颜色
#使用函数cv2.inRange()将某个图像内的在[100,200]内的值标注出来
import cv2
import numpy as np
img=np.random.randint(0,256,[5,5],dtype=np.uint8)
min=100
max=200
mask=cv2.inRange(img,min,max)
print("img=\n",img)
print("mask=\n",mask)

img=
 [[179  11 147  60 213]
 [160 111  34  37 184]
 [221  30 178 236 179]
 [249 132  92   3 159]
 [113 151 137 115 159]]
mask=
 [[255   0 255   0   0]
 [255 255   0   0 255]
 [  0   0 255   0 255]
 [  0 255   0   0 255]
 [255 255 255 255 255]]


In [6]:
#通过基于掩码的按位与显示ROI
import cv2
import numpy as np
img=np.ones([5,5],dtype=np.uint8)*9
mask=np.zeros([5,5],dtype=np.uint8)
mask[0:3,0]=1
mask[2:5,2:4]=1
roi=cv2.bitwise_and(img,img,mask=mask)
print("img=\n",img)
print("mask=\n",mask)
print("roi=\n",roi)

img=
 [[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]
mask=
 [[1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 1 1 0]
 [0 0 1 1 0]
 [0 0 1 1 0]]
roi=
 [[9 0 0 0 0]
 [9 0 0 0 0]
 [9 0 9 9 0]
 [0 0 9 9 0]
 [0 0 9 9 0]]


In [7]:
#显示特定颜色值
import cv2
import numpy as np
opencv=cv2.imread("opencv.png",-1)
hsv=cv2.cvtColor(opencv,cv2.COLOR_BGR2HSV)
cv2.imshow("opencv",opencv)
#=============指定蓝色值得范围===============###
minBlue=np.array([110,100,100])
maxBlue=np.array([130,255,255])
#确定蓝色区域
mask=cv2.inRange(hsv,minBlue,maxBlue)
#通过掩码控制得按位与运算，锁定蓝色区域
Blue=cv2.bitwise_and(opencv,opencv,mask=mask)
cv2.imshow("Blue",Blue)
#=============指定绿色值得范围===============###
minGreen=np.array([50,100,100])
maxGreen=np.array([70,255,255])
#确定绿色区域
mask=cv2.inRange(hsv,minGreen,maxGreen)
#通过掩码控制得按位与运算，锁定绿色区域
Green=cv2.bitwise_and(opencv,opencv,mask=mask)
cv2.imshow("Green",Green)
#=============指定红色值得范围===============###
minRed=np.array([0,50,50])
maxRed=np.array([30,255,255])
#确定红色区域
mask=cv2.inRange(hsv,minRed,maxRed)
#通过掩码控制得按位与运算，锁定红色区域
Red=cv2.bitwise_and(opencv,opencv,mask=mask)
cv2.imshow("Red",Red)
cv2.waitKey()
cv2.destroyAllWindows()

In [8]:
#实现艺术效果
import cv2
img=cv2.imread("lena.png",-1)
hsv=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
h,s,v=cv2.split(hsv)
v[:,:]=255
newHSV=cv2.merge([h,s,v])
art=cv2.cvtColor(newHSV,cv2.COLOR_HSV2BGR)
cv2.imshow("img",img)
cv2.imshow("art",art)
cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
#4.5 alpha通道
import cv2
img=cv2.imread("lena.png",-1)
bgra=cv2.cvtColor(img,cv2.COLOR_BGR2BGRA)
b,g,r,a=cv2.split(bgra)
a[:,:]=125
bgra125=cv2.merge([b,g,r,a])
a[:,:]=0
bgra0=cv2.merge([b,g,r,a])
cv2.imwrite("bgra.png",bgra)
cv2.imwrite("bgra125.png",bgra125)
cv2.imwrite("bgra0.png",bgra0)
cv2.imshow("img",img)
cv2.imshow("bgra",bgra)
cv2.imshow("bgra125",bgra125)
cv2.imshow("bgra0",bgra0)
cv2.waitKey()
cv2.destroyAllWindows()