In [1]:
#9.2 Sobel算子
#使用cv2.convertScaleAbs()对一个随机数组取绝对值
import cv2
import numpy as np
img=np.random.randint(-256,256,[4,5],np.int16)
rst=cv2.convertScaleAbs(img)
print("img=\n",img)
print("rst=\n",rst)

img=
 [[ -87  110 -169   85 -208]
 [ -23 -197   -6 -146    1]
 [ -53   -5  183  196  147]
 [-168 -214  -88  206  232]]
rst=
 [[ 87 110 169  85 208]
 [ 23 197   6 146   1]
 [ 53   5 183 196 147]
 [168 214  88 206 232]]


In [2]:
#方向
#计算X方向梯度：dx=1,dy=0 ,计算Y方向梯度：dx=0,dy=1
#计算X方向和Y方向的边缘叠加，需分别计算两个方向的，然后二者相加 cv2.addWeighted()
#实例：使用cv2.Sobel()获取图像水平方向的边缘信息
import cv2
o=cv2.imread("lena.png",0)
Sobelx=cv2.Sobel(o,cv2.CV_64F,1,0)
Sobelx=cv2.convertScaleAbs(Sobelx)
cv2.imshow("original",o)
cv2.imshow("Sobelx",Sobelx)
cv2.waitKey()
cv2.destroyAllWindows()

In [3]:
#实例：使用cv2.Sobel()获取图像垂直方向的边缘信息
import cv2
o=cv2.imread("lena.png",0)
Sobely=cv2.Sobel(o,cv2.CV_64F,0,1)
Sobely=cv2.convertScaleAbs(Sobely)
cv2.imshow("original",o)
cv2.imshow("Sobely",Sobely)
cv2.waitKey()
cv2.destroyAllWindows()

In [4]:
#实例：使用cv2.Sobel()获取图像水平和垂直方向的边缘信息
import cv2
o=cv2.imread("lena.png",0)
Sobelx=cv2.Sobel(o,cv2.CV_64F,1,0)
Sobelx=cv2.convertScaleAbs(Sobelx)
Sobely=cv2.Sobel(o,cv2.CV_64F,0,1)
Sobely=cv2.convertScaleAbs(Sobely)
Sobelxy=cv2.addWeighted(Sobelx,0.5,Sobely,0.5,0)
cv2.imshow("original",o)
cv2.imshow("Sobelx",Sobelx)
cv2.imshow("Sobely",Sobely)
cv2.imshow("Sobelxy",Sobelxy)
cv2.waitKey()
cv2.destroyAllWindows()

In [5]:
#9.3 Scharr算子
import cv2
o=cv2.imread("lena.png",0)
Sobelx=cv2.Sobel(o,cv2.CV_64F,1,0)
Sobelx=cv2.convertScaleAbs(Sobelx)
Sobely=cv2.Sobel(o,cv2.CV_64F,0,1)
Sobely=cv2.convertScaleAbs(Sobely)
Sobelxy=cv2.addWeighted(Sobelx,0.5,Sobely,0.5,0)
Scharrx=cv2.Scharr(o,cv2.CV_64F,1,0)
Scharrx=cv2.convertScaleAbs(Scharrx)
Scharry=cv2.Scharr(o,cv2.CV_64F,0,1)
Scharry=cv2.convertScaleAbs(Scharry)
Scharrxy=cv2.addWeighted(Scharrx,0.5,Scharry,0.5,0)
cv2.imshow("original",o)
cv2.imshow("Sobelx",Sobelx)
cv2.imshow("Sobely",Sobely)
cv2.imshow("Sobelxy",Sobelxy)
cv2.imshow("Scharrx",Scharrx)
cv2.imshow("Scharry",Scharry)
cv2.imshow("Scharrxy",Scharrxy)
cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
#9.5 Laplacian算子
#不用分别计算X和Y方向上的梯度
import cv2
o=cv2.imread("lena.png",0)
Laplacian=cv2.Laplacian(o,cv2.CV_64F)
Laplacian=cv2.convertScaleAbs(Laplacian)
cv2.imshow("original",o)
cv2.imshow("Laplacian",Laplacian)
cv2.waitKey()
cv2.destroyAllWindows()