In [1]:
#2.2 像素处理
#2.2.1 二值图像及灰度图像
#使用Numpy库来生成一个元素值都是0的二维数组，用来模拟一副黑色图像，并对其进行修改访问
import cv2
import numpy as np
img=np.zeros((8,8),dtype=np.uint8)
print("img=\n",img)
print("读取像素点[0，3]=",img[0,3])
img[0,3]=255
print("修改后img=\n",img)
print("读取修改后像素点[0，3]=",img[0,3])
cv2.imshow("two",img)
cv2.waitKey()
cv2.destroyAllWindows()

img=
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
读取像素点[0，3]= 0
修改后img=
 [[  0   0   0 255   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]]
读取修改后像素点[0，3]= 255


In [2]:
#读取一个灰度图像，对其像素进行修改访问
import cv2
lena=cv2.imread("lena.jpg",0)
cv2.imshow("before",lena)
for i in range(10,100):
    for j in range(80,100):
        lena[i,j]=255
cv2.imshow("after",lena)
cv2.waitKey()
cv2.destroyAllWindows()

In [3]:
#2.2.2 彩色图像
#使用numpy生成三维数组，用来观察三个通道的变化情况
import cv2
import numpy as np
#####------------蓝色通道--------------#######
blue=np.zeros((300,300,3),dtype=np.uint8)
blue[:,:,0]=255
print("blue=\n",blue)
cv2.imshow("blue",blue)
#####-------------绿色通道-------------####
green=np.zeros((300,300,3),dtype=np.uint8)
green[:,:,1]=255
print("green=\n",green)
cv2.imshow("green",green)
#####--------------红色通道-----------#########
red=np.zeros((300,300,3),dtype=np.uint8)
red[:,:,2]=255
print("red=\n",red)
cv2.imshow("red",red)
####---------------释放窗口--------------####
cv2.waitKey()
cv2.destroyAllWindows()

blue=
 [[[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 ...

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]]
green=
 [[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [  

In [1]:
#使用numpy生成三维数组，用来观察三个通道的变化情况
import cv2
import numpy as np
img=np.zeros((300,300,3),dtype=np.uint8)
img[:,0:100,0]=255
img[:,100:200,1]=255
img[:,200:300,2]=255
print("img\n",img)
cv2.imshow("img",img)
cv2.waitKey()
cv2.destroyAllWindows()

img
 [[[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 ...

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]]


In [2]:
#使用numpy生成三维数组，用来模拟一幅BGR模式的彩色图像，并对其像素进行修改访问
import numpy as np
img=np.zeros((2,4,3),dtype=np.uint8)
print("img=\n",img)
print("读取像素点img[0,3]=",img[0,3])
print("读取像素点img[1,2,2]=",img[1,2,2])
img[0,3]=255
img[0,0]=[66,77,88]
img[1,1,1]=3
img[1,2,2]=4
img[0,2,0]=5
print("修改后的img=\n",img)
print("修改后的像素点img[1,2,2]=",img[1,2,2])

img=
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
读取像素点img[0,3]= [0 0 0]
读取像素点img[1,2,2]= 0
修改后的img=
 [[[ 66  77  88]
  [  0   0   0]
  [  5   0   0]
  [255 255 255]]

 [[  0   0   0]
  [  0   3   0]
  [  0   0   4]
  [  0   0   0]]]
修改后的像素点img[1,2,2]= 4


In [3]:
#读取一幅彩色图像，并对其像素进行修改访问
import cv2
import numpy as np
img=cv2.imread("lena.png",-1)
cv2.imshow("before",img)
print("访问img[0,0]=",img[0,0])
print("访问img[0,0,0]=",img[0,0,0])
print("访问img[0,0,1]=",img[0,0,1])
print("访问img[0,0,2]=",img[0,0,2])
print("访问img[50,0]=",img[50,0])
print("访问img[100,0]=",img[100,0])
###区域1
for i in range(0,50):
    for j in range(0,100):
        for k in range(0,3):
            img[i,j,k]=255   ##白色
###区域2
for i in range(50,100):
    for j in range(0,100):
        for k in range(0,3):
            img[i,j,k]=128   ###灰色
###区域3
for i in range(100,150):
    for j in range(0,100):
        for k in range(0,3):
            img[i,j,k]=0    ####黑色
cv2.imshow("after",img)
print("修改后img[0,0]=",img[0,0])
print("修改后img[0,0,0]=",img[0,0,0])
print("修改后img[0,0,1]=",img[0,0,1])
print("修改后img[0,0,2]=",img[0,0,2])
print("修改后img[50,0]=",img[50,0])
print("修改后img[100,0]=",img[100,0])
cv2.waitKey()
cv2.destroyAllWindows()

访问img[0,0]= [ 78 115 195]
访问img[0,0,0]= 78
访问img[0,0,1]= 115
访问img[0,0,2]= 195
访问img[50,0]= [ 77 109 192]
访问img[100,0]= [ 82 115 195]
修改后img[0,0]= [255 255 255]
修改后img[0,0,0]= 255
修改后img[0,0,1]= 255
修改后img[0,0,2]= 255
修改后img[50,0]= [128 128 128]
修改后img[100,0]= [0 0 0]


In [4]:
#2.3 使用numpy.array访问像素
###########灰度图像和彩色图像########
#2.3.1 二值图像及灰度图像
#使用Numpy生成一个二维随机数组，用来模拟一幅灰度图像，并对其像素进行修改访问
import cv2
import numpy as np
img=np.random.randint(10,99,size=[5,5],dtype=np.uint8)
print("img=\n",img)
print("读取像素点img.item(3,2)=",img.item(3,2))
img.itemset((3,2),255)
print("修改后img=\n",img)
print("修改后像素点img.item(3,2)=",img.item(3,2))

img=
 [[57 70 97 27 30]
 [93 40 65 22 52]
 [40 61 37 10 70]
 [95 73 82 31 42]
 [44 95 52 64 15]]
读取像素点img.item(3,2)= 82
修改后img=
 [[ 57  70  97  27  30]
 [ 93  40  65  22  52]
 [ 40  61  37  10  70]
 [ 95  73 255  31  42]
 [ 44  95  52  64  15]]
修改后像素点img.item(3,2)= 255


In [5]:
#生成一个灰度图像，让其中的像素值均为随机数
import cv2
import numpy as np
img=np.random.randint(0,256,size=[256,256],dtype=np.uint8)
cv2.imshow("demo",img)
cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
#读取一幅灰度图像，并对其像素进行修改访问
import cv2
img=cv2.imread("lena.png",0)
#测试修改、读取单个像素值
print("读取像素点img.item(3,2)=",img.item(3,2))
img.itemset((3,2),255)
print("修改后像素点img.item(3,2)=",img.item(3,2))
#测试修改一个区域的像素值
cv2.imshow("before",img)
for i in range(10,100):
    for j in range(80,100):
        img.itemset((i,j),255)
cv2.imshow("after",img)
cv2.waitKey()
cv2.destroyAllWindows()

读取像素点img.item(3,2)= 134
修改后像素点img.item(3,2)= 255


In [7]:
#2.3.2彩色图像
#使用Numpy生成一个由随机数组成的三维数组，用来模拟一幅RGB彩色空间的彩色图像，并使用函数item()和itemset()来访问和修改它
import numpy as np
img=np.random.randint(10,99,size=[2,4,3],dtype=np.uint8)
print("img=\n",img)
print("读取像素点img[1,2,0]=",img.item(1,2,0))
print("读取像素点img[0,2,1]=",img.item(0,2,1))
print("读取像素点img[1,0,2]=",img.item(1,0,2))
img.itemset((1,2,0),255)
img.itemset((0,2,1),255)
img.itemset((1,0,2),255)
print("修改后img=\n",img)
print("修改后像素点img[1,2,0]=",img.item(1,2,0))
print("修改后像素点img[0,2,1]=",img.item(0,2,1))
print("修改后像素点img[1,0,2]=",img.item(1,0,2))

img=
 [[[74 41 37]
  [61 57 11]
  [85 46 44]
  [29 96 80]]

 [[16 84 62]
  [88 12 49]
  [38 56 40]
  [79 79 14]]]
读取像素点img[1,2,0]= 38
读取像素点img[0,2,1]= 46
读取像素点img[1,0,2]= 62
修改后img=
 [[[ 74  41  37]
  [ 61  57  11]
  [ 85 255  44]
  [ 29  96  80]]

 [[ 16  84 255]
  [ 88  12  49]
  [255  56  40]
  [ 79  79  14]]]
修改后像素点img[1,2,0]= 255
修改后像素点img[0,2,1]= 255
修改后像素点img[1,0,2]= 255


In [8]:
#生成一幅彩色图像，让其中的像素值均为随机数
import cv2
import numpy as np
img=np.random.randint(0,256,size=[256,256,3],dtype=np.uint8)
cv2.imshow("demo",img)
cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
#2.4 感兴趣区域ROI
#获取图像lena的脸部信息，并将其显示出来
import cv2
import numpy as np
a=cv2.imread("lena.png",cv2.IMREAD_UNCHANGED)
face=a[110:250,130:230]
cv2.imshow("original",a)
cv2.imshow("face",face)
cv2.waitKey()
cv2.destroyAllWindows()

In [10]:
#对脸部进行打码
import cv2
import numpy as np
face=np.random.randint(0,256,size=[140,100,3])
a[110:250,130:230]=face
cv2.imshow("result",a)
cv2.waitKey()
cv2.destroyAllWindows()

In [11]:
##2.5 通道操作
#2.5.1 通道拆分
lena=cv2.imread("lena.png",-1)
cv2.imshow("lena",lena)
b=lena[:,:,0]
g=lena[:,:,1]
r=lena[:,:,2]
cv2.imshow("b",b)
cv2.imshow("g",g)
cv2.imshow("r",r)
lena[:,:,0]=0
cv2.imshow("lenab0",lena)
lena[:,:,1]=0
cv2.imshow("lenab0g0",lena)
cv2.waitKey()
cv2.destroyAllWindows()

In [12]:
#通过函数拆分通道
import cv2
lena=cv2.imread("lena.png",-1)
b,g,r=cv2.split(lena)
cv2.imshow("B",b)
cv2.imshow("G",g)
cv2.imshow("R",r)
cv2.waitKey()
cv2.destroyAllWindows()

In [13]:
#2.5.2 通道合并
import cv2
lena=cv2.imread("lena.png",-1)
b,g,r=cv2.split(lena)
bgr=cv2.merge([b,g,r])
rgb=cv2.merge([r,g,b])
cv2.imshow("lena",lena)
cv2.imshow("bgr",bgr)
cv2.imshow("rgb",rgb)
cv2.waitKey()
cv2.destroyAllWindows()

In [16]:
##2.6 获取图像属性
import cv2
gray=cv2.imread("lena.png",0)
color=cv2.imread("lena.png",-1)
print("图像gray的属性：")
print("gray.shape=",grey.shape)
print("gray.size=",grey.size)
print("gray.dtype=",grey.dtype)
print("图像color的属性：")
print("color.shape=",color.shape)
print("color.size=",color.size)
print("color.dtype=",color.dtype)

图像gray的属性：
gray.shape= (300, 300)
gray.size= 90000
gray.dtype= uint8
图像color的属性：
color.shape= (300, 300, 3)
color.size= 270000
color.dtype= uint8
