In [2]:
#12.1 查找并绘制轮廓 cv2.findContours() cv2.drawContour()
#背景为黑
import cv2
o=cv2.imread("contours1.jpg",-1)
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
img,contours,hierarchy=cv2.findContours(binary,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
o=cv2.drawContours(o,contours,-1,(0,0,255),5)
cv2.imshow("result",o)
cv2.waitKey()
cv2.destroyAllWindows()

In [3]:
#背景为白
import cv2
o=cv2.imread("contours2.jpg",-1)
cv2.imshow("original",o)
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY_INV)
img,contours,hierarchy=cv2.findContours(binary,cv2.RETR_CCOMP,cv2.CHAIN_APPROX_SIMPLE)
o=cv2.drawContours(o,contours,-1,(0,0,0),5)
cv2.imshow("result",o)
cv2.waitKey()
cv2.destroyAllWindows()

In [4]:
#逐个显示一幅图像中的边缘信息
import cv2
import numpy as np
o=cv2.imread("contours2.jpg",-1)
cv2.imshow("original",o)
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY_INV)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
n=len(contours)
contoursImg=[]
for i in range(n):
    temp=np.ones(o.shape,np.uint8)*225
    contoursImg.append(temp)
    contoursImg[i]=cv2.drawContours(contoursImg[i],contours,i,(0,0,0),5)
    cv2.imshow("contours["+ str(i)+"]",contoursImg[i])
cv2.waitKey()
cv2.destroyAllWindows()

In [5]:
#使用轮廓绘制功能，提取前景对象
#黑背景
import cv2
import numpy as np
o=cv2.imread("lena.jpg",-1)
cv2.imshow("original",o)
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,bindary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
image,contours,hierarchy=cv2.findContours(bindary,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
mask=np.zeros(o.shape,np.uint8)
mask=cv2.drawContours(mask,contours,-1,(255,255,255),-1)
cv2.imshow("mask",mask)
loc=cv2.bitwise_and(o,mask)
cv2.imshow("location",loc)
cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
#白背景
import cv2
import numpy as np
o=cv2.imread("contours2.jpg",-1)
cv2.imshow("original",o)
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,bindary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY_INV)
image,contours,hierarchy=cv2.findContours(bindary,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
mask=np.ones(o.shape,np.uint8)*255
mask=cv2.drawContours(mask,contours,-1,(0,0,0),-1)
cv2.imshow("mask",mask)
loc=cv2.bitwise_and(o,mask)
cv2.imshow("location",loc)
cv2.waitKey()
cv2.destroyAllWindows()

In [7]:
#12.2 矩特征
#12.2.1 矩的计算：moments函数
#使用函数cv2.moments()提取一幅图像的特征
import cv2
import numpy as np
o=cv2.imread("contours2.jpg",-1)
cv2.imshow("original",o)
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY_INV)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
n=len(contours)
contoursImg=[]
for i in range(n):
    temp=np.ones(o.shape,np.uint8)*255
    contoursImg.append(temp)
    contoursImg[i]=cv2.drawContours(contoursImg[i],contours,i,3)
    cv2.imshow("Contours[" + str(i)+"]",contoursImg[i])
print("观察各个轮廓的矩（moments）:")
for i in range(n):
    print("轮廓"+str(i)+"的矩：\n",cv2.moments(contours[i]))
print("观察各个轮廓的面积：")
for i in range(n):
    print("轮廓"+str(i)+"的面积:%d" %cv2.moments(contours[i])['m00'])
cv2.waitKey()
cv2.destroyAllWindows()

观察各个轮廓的矩（moments）:
轮廓0的矩：
 {'m00': 23619.0, 'm10': 8259487.5, 'm01': 7842277.0, 'm20': 2981320587.0, 'm11': 2742418082.25, 'm02': 2628607420.5, 'm30': 1107604995834.75, 'm21': 990893377808.8833, 'm12': 919215355531.0834, 'm03': 889021597839.9, 'mu20': 93004664.96027565, 'mu11': -684.5495047569275, 'mu02': 24716123.462487698, 'mu30': 22839.223876953125, 'mu21': 998354268.4946594, 'mu12': 342398.71873283386, 'mu03': -174764789.10766602, 'nu20': 0.16671770385372114, 'nu11': -1.2271053463395935e-06, 'nu02': 0.04430546955457599, 'nu30': 2.6639592437021495e-07, 'nu21': 0.01164476996405119, 'nu12': 3.993726917842135e-06, 'nu03': -0.0020384505091997577}
轮廓1的矩：
 {'m00': 23369.5, 'm10': 4044902.333333333, 'm01': 6780924.5, 'm20': 741028567.4166666, 'm11': 1144132724.7083333, 'm02': 2042633212.25, 'm30': 141906239505.2, 'm21': 205455036307.36667, 'm12': 336233561854.06665, 'm03': 635190941480.35, 'mu20': 40917958.02384949, 'mu11': -29541394.644120455, 'mu02': 75071344.22970653, 'mu30': -518992920

In [8]:
#12.2.2 计算轮廓的面积：contourArea 函数
import cv2
import numpy as np
o=cv2.imread("contours2.jpg",-1)
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY_INV)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
n=len(contours)
contoursImg=[]
for i in range(n):
    print("contours["+str(i)+"]面积:",cv2.contourArea(contours[i]))
    temp=np.ones(o.shape,np.uint8)*255
    contoursImg.append(temp)
    contoursImg[i]=cv2.drawContours( contoursImg[i],contours,i,(0,0,0),3)
    cv2.imshow("contours["+str(i)+"]",contoursImg[i])
cv2.waitKey()
cv2.destroyAllWindows()

contours[0]面积: 23619.0
contours[1]面积: 23369.5
contours[2]面积: 23023.5


In [9]:
#将面积大于23500的轮廓筛选出来
import cv2
import numpy as np
o=cv2.imread("contours2.jpg",-1)
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY_INV)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
n=len(contours)
contoursImg=[]
for i in range(n):
    print("contours["+str(i)+"]面积:",cv2.contourArea(contours[i]))
    temp=np.ones(o.shape,np.uint8)*255
    contoursImg.append(temp)
    contoursImg[i]=cv2.drawContours( contoursImg[i],contours,i,(0,0,0),3)
    if cv2.contourArea(contours[i])>23500:
        cv2.imshow("contours["+str(i)+"]",contoursImg[i])
cv2.waitKey()
cv2.destroyAllWindows()

contours[0]面积: 23619.0
contours[1]面积: 23369.5
contours[2]面积: 23023.5


In [10]:
#12.2.3 计算轮廓的长度：arcLength函数
import cv2
import numpy as np
#===============读取并显示原始图像==========================###
o=cv2.imread("contours2.jpg",-1)
cv2.imshow("original",o)
#================获取轮廓==================================###
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY_INV)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
#===============计算各轮廓的长度之和、平均长度===============###
n=len(contours)   #获取轮廓的个数
cnLen=[]          #存储个轮廓的长度
for i in range(n):
    cnLen.append(cv2.arcLength(contours[i],True))
    print("第"+str(i)+"个轮廓的长度:%d" %cnLen[i])
cnLenSum=np.sum(cnLen)   #各轮廓的长度之和
cnLenAvr=cnLenSum/n      #轮廓长度的平均值
print("轮廓的总长度为：%d" %cnLenSum)
print("轮廓的平均长度为：%d" %cnLenAvr)
#==============显示长度超过平均值的轮廓======================###
contoursImg=[]
for i in range(n):
    temp=np.ones(o.shape,np.uint8)*255
    contoursImg.append(temp)
    contoursImg[i]=cv2.drawContours(contoursImg[i],contours,i,(0,0,0),3)
    if cv2.arcLength(contours[i],True)>cnLenAvr:
        cv2.imshow("contours["+str(i)+"]",contoursImg[i])
cv2.waitKey()
cv2.destroyAllWindows()

第0个轮廓的长度:696
第1个轮廓的长度:716
第2个轮廓的长度:707
轮廓的总长度为：2120
轮廓的平均长度为：706


In [11]:
#12.3 Hu矩
#12.3.1 Hu 矩函数
#计算三幅不同图像的Hu矩，并进行比较
import cv2
import numpy as np
#=============================计算o1的 Hu矩==================###
o1=cv2.imread("lena.png",-1)
gray1=cv2.cvtColor(o1,cv2.COLOR_BGR2GRAY)
HuM1=cv2.HuMoments(cv2.moments(gray1)).flatten()
#=============================计算o2的 Hu矩==================###
o2=cv2.imread("lenax.png",-1)
gray2=cv2.cvtColor(o2,cv2.COLOR_BGR2GRAY)
HuM2=cv2.HuMoments(cv2.moments(gray2)).flatten()
#=============================计算o3的 Hu矩==================###
o3=cv2.imread("lenay.png",-1)
gray3=cv2.cvtColor(o3,cv2.COLOR_BGR2GRAY)
HuM3=cv2.HuMoments(cv2.moments(gray3)).flatten()
#=============================计算o4的 Hu矩==================###
o4=cv2.imread("opencv.png",-1)
gray4=cv2.cvtColor(o4,cv2.COLOR_BGR2GRAY)
HuM4=cv2.HuMoments(cv2.moments(gray4)).flatten()
#=========打印图像o1、o2、o3、o4 的特征值======================###
print("o1.shape=",o1.shape)
print("o2.shape=",o2.shape)
print("o3.shape=",o3.shape)
print("o4.shape=",o4.shape)
print("cv2.moments(gray1)=\n",cv2.moments(gray1))
print("cv2.moments(gray2)=\n",cv2.moments(gray2))
print("cv2.moments(gray3)=\n",cv2.moments(gray3))
print("cv2.moments(gray4)=\n",cv2.moments(gray4))
print("\nHuM1=\n",HuM1)
print("\nHuM2=\n",HuM2)
print("\nHuM3=\n",HuM3)
print("\nHuM4=\n",HuM4)
#=============计算图像o1与o2、o3、o4的Hu矩之差==================###
print("\nHuM1-HuM2=",HuM1-HuM2)
print("\nHuM1-HuM3=",HuM1-HuM3)
print("\nHuM1-HuM4=",HuM1-HuM4)
#===================显示图像===================================###
cv2.imshow("original1",o1)
cv2.imshow("original2",o2)
cv2.imshow("original3",o3)
cv2.imshow("original4",o4)
cv2.waitKey()
cv2.destroyAllWindows()

o1.shape= (300, 300, 3)
o2.shape= (300, 300, 3)
o3.shape= (300, 300, 3)
o4.shape= (1118, 908, 4)
cv2.moments(gray1)=
 {'m00': 8607601.0, 'm10': 1359613552.0, 'm01': 1244180502.0, 'm20': 277757544802.0, 'm11': 200995298199.0, 'm02': 244691703902.0, 'm30': 62690303277658.0, 'm21': 41888997703993.0, 'm12': 40041482763801.0, 'm03': 54640948566582.0, 'mu20': 62999796297.85153, 'mu11': 4470776249.926941, 'mu02': 64852382637.34427, 'mu30': -1085152360056.0547, 'mu21': 328337831310.62695, 'mu12': 98755171634.71875, 'mu03': 524036436561.1172, 'nu20': 0.0008503053087625562, 'nu11': 6.0341858275692125e-05, 'nu02': 0.0008753095800774046, 'nu30': -4.9921244210457105e-06, 'nu21': 1.5104821833076953e-06, 'nu12': 4.5431233637714597e-07, 'nu03': 2.4107721540036916e-06}
cv2.moments(gray2)=
 {'m00': 8607601.0, 'm10': 1359613552.0, 'm01': 1329492197.0, 'm20': 277757544802.0, 'm11': 205529153849.0, 'm02': 270199900707.0, 'm30': 62690303277658.0, 'm21': 41160508191805.0, 'm12': 41397105603151.0, 'm03': 6124

In [12]:
#12.3.2 形状匹配 cv2.matchShapes()
#准备三幅图像
import cv2
import numpy as np
o=cv2.imread("contours6.jpg",-1)
r=cv2.pyrDown(o)
r1=cv2.flip(r,0)
k=np.ones((20,20),np.float32)
r2=cv2.erode(r,k)
cv2.imwrite("contours6_down.jpg",r)
cv2.imwrite("contours6x.jpg",r1)
cv2.imwrite("contours6_erode.jpg",r2)
cv2.imshow("o",o)
cv2.imshow("r",r)
cv2.imshow("r1",r1)
cv2.imshow("r2",r2)
cv2.waitKey()
cv2.destroyAllWindows()

In [13]:
#使用cv2.matchShapes()计算三幅图像的匹配度
import cv2
o1=cv2.imread("contours6_down.jpg",-1)
o2=cv2.imread("contours6x.jpg",-1)
o3=cv2.imread("contours6_erode.jpg",-1)
o4=cv2.imread("lena.jpg",-1)
gray1=cv2.cvtColor(o1,cv2.COLOR_BGR2GRAY)
gray2=cv2.cvtColor(o2,cv2.COLOR_BGR2GRAY)
gray3=cv2.cvtColor(o3,cv2.COLOR_BGR2GRAY)
gray4=cv2.cvtColor(o4,cv2.COLOR_BGR2GRAY)
ret,binary1=cv2.threshold(gray1,127,255,cv2.THRESH_BINARY)
ret,binary2=cv2.threshold(gray2,127,255,cv2.THRESH_BINARY)
ret,binary3=cv2.threshold(gray3,127,255,cv2.THRESH_BINARY)
ret,binary4=cv2.threshold(gray4,127,255,cv2.THRESH_BINARY)
image,contours1,hierarchy=cv2.findContours(binary1,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
image,contours2,hierarchy=cv2.findContours(binary2,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
image,contours3,hierarchy=cv2.findContours(binary3,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
image,contours4,hierarchy=cv2.findContours(binary4,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
cnt1=contours1[0]
cnt2=contours2[0]
cnt3=contours3[0]
cnt4=contours4[0]
ret0=cv2.matchShapes(cnt1,cnt1,1,0.0)
ret1=cv2.matchShapes(cnt1,cnt2,1,0.0)
ret2=cv2.matchShapes(cnt1,cnt3,1,0.0)
ret3=cv2.matchShapes(cnt1,cnt4,1,0.0)
print("相同图像的matchShape=",ret0)
print("相似图像的matchShape=",ret1)
print("相似图像的matchShape=",ret2)
print("不同图像的matchShape=",ret3)

相同图像的matchShape= 0.0
相似图像的matchShape= 1.7976931348623157e+308
相似图像的matchShape= 0.7642945113085422
不同图像的matchShape= 1.7976931348623157e+308


In [14]:
#12.4 轮廓拟合
#12.4.1 矩形包围框 cv2.boundingRect()
#显示cv2.boundingRect()不同形式的返回值
import cv2
#=============================读取并显示原始图像=======================###
o=cv2.imread("contours3_one.jpg",-1)
#=============================提取图像轮廓=============================###
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
#===========================返回顶点及边长=============================###
x,y,w,h=cv2.boundingRect(contours[0])
print("顶点及长宽的点形式：")
print("x=",x)
print("y=",y)
print("w=",w)
print("h=",h)
#========================仅有一个返回值的情况===========================###
rect=cv2.boundingRect(contours[0])
print("\n顶点及长宽的元组(tuple)形式:")
print("rect=",rect)

顶点及长宽的点形式：
x= 110
y= 20
w= 127
h= 56

顶点及长宽的元组(tuple)形式:
rect= (110, 20, 127, 56)


In [15]:
#使用函数cv2.drawContours()绘制矩形包围框
import cv2
import numpy as np
#=========================读取并显示原始图像============================###
o=cv2.imread("contours3_one.jpg",-1)
cv2.imshow("original",o)
#=========================提取图像轮廓===============================###
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
#==========================构造矩形边界==============================###
x,y,w,h=cv2.boundingRect(contours[0])
brcnt=np.array([[[x,y]],[[x+w,y]],[[x+w,y+h]],[[x,y+h]]])
cv2.drawContours(o,[brcnt],-1,(255,255,255),2)
#==========================显示矩形边界===============================###
cv2.imshow("result",o)
cv2.waitKey()
cv2.destroyAllWindows()

In [16]:
#使用函数cv2.boundingRect()及cv2.rectangle()绘制矩形包围框
import cv2
#=========================读取并显示原始图像============================###
o=cv2.imread("contours3_one.jpg",-1)
cv2.imshow("original",o)
#=========================提取图像轮廓===============================###
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
#==========================构造矩形边界==============================###
x,y,w,h=cv2.boundingRect(contours[0])
cv2.rectangle(o,(x,y),(x+w,y+h),(255,255,255),2)
#==========================显示矩形边界===============================###
cv2.imshow("result",o)
cv2.waitKey()
cv2.destroyAllWindows()

In [17]:
#12.4.2 最小包围矩形框
#使用cv2.minAreaRect() 函数计算图像的最小包围矩形框
import cv2
import numpy as np
o=cv2.imread("contours3_one.jpg",-1)
cv2.imshow("original",o)
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
rect=cv2.minAreaRect(contours[0])
print("返回值rect:\n",rect)
points=cv2.boxPoints(rect)
print("\n转换后的points:\n",points)
points=np.int0(points)   #取整
print("\n取整后的points:\n",points)
image=cv2.drawContours(o,[points],0,(255,255,255),2)
cv2.imshow("result",o)
cv2.waitKey()
cv2.destroyAllWindows()

返回值rect:
 ((173.0, 47.5), (126.0, 55.0), -0.0)

转换后的points:
 [[110.  75.]
 [110.  20.]
 [236.  20.]
 [236.  75.]]

取整后的points:
 [[110  75]
 [110  20]
 [236  20]
 [236  75]]


In [18]:
#12.4.3 最小包围圆圈
#使用cv2.minEnclosingCircle()构造图像的最小包围圆圈
import cv2
import numpy as np
o=cv2.imread("contours3_one.jpg",-1)
cv2.imshow("original",o)
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
(x,y),radius=cv2.minEnclosingCircle(contours[0])
center=(int(x),int(y))
radius=int(radius)
cv2.circle(o,center,radius,(255,255,255),2)
cv2.imshow("result",o)
cv2.waitKey()
cv2.destroyAllWindows()

In [19]:
#12.4.4 最优拟合椭圆
#使用cv2.ellipse()根据函数cv2.fitEllipse()的返回值绘制最优拟合椭圆
import cv2
o=cv2.imread("contours3_one.jpg",-1)
cv2.imshow("original",o)
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
ellipse=cv2.fitEllipse(contours[0])
print("ellipse=",ellipse)
cv2.ellipse(o,ellipse,(0,255,0),3)
cv2.imshow("result",o)
cv2.waitKey()
cv2.destroyAllWindows()

ellipse= ((170.41552734375, 49.87754440307617), (58.2590446472168, 111.68458557128906), 80.60287475585938)


In [20]:
#12.4.5 最优拟合直线
#使用函数cv2.fitLine()构造最优拟合曲线
o=cv2.imread("contours3_one.jpg",-1)
cv2.imshow("original",o)
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
rows,cols=image.shape[:2]
[vx,vy,x,y]=cv2.fitLine(contours[0],cv2.DIST_L2,0,0.01,0.01)
lefty=int((-x*vy/vx)+y)
righty=int(((cols-x)*vy/vx)+y)
cv2.line(o,(cols-1,righty),(0,lefty),(0,255,0),2)
cv2.imshow("result",o)
cv2.waitKey()
cv2.destroyAllWindows()

In [21]:
#12.4.6 最小外包三角
#使用函数cv2.minEnclosingTriangle()构造最小外包三角形
o=cv2.imread("contours3_one.jpg",-1)
cv2.imshow("original",o)
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
area,trg1=cv2.minEnclosingTriangle(contours[0])
print("area=",area)
print("trg1:",trg1)
for i in range(0,3):
    cv2.line(o,tuple(trg1[i][0]),tuple(trg1[(i+1) % 3][0]),(255,255,255),2)
cv2.imshow("result",o)
cv2.waitKey()
cv2.destroyAllWindows()

area= 7875.21875
trg1: [[[270.7143    75.      ]]

 [[172.73334  -10.733334]]

 [[ 87.        75.      ]]]


In [22]:
#12.4.7 逼近多边形
#使用函数cv2.approxPolyDP()构造不同精度的逼近多边形
import cv2
##=====================读取并显示原始图像==========================##
o=cv2.imread("contours3_one.jpg",-1)
cv2.imshow("original",o)
##======================获取轮廓==================================###
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
##======================epsilon=0.1*周长=========================###
adp=o.copy()    
epsilon=0.1*cv2.arcLength(contours[0],True)
approx=cv2.approxPolyDP(contours[0],epsilon,True)
adp=cv2.drawContours(adp,[approx],0,(0,0,225),2)
cv2.imshow("result0.1",adp)
##====================epsilon=0.09*周长===========================###
adp=o.copy()
epsilon=0.09*cv2.arcLength(contours[0],True)
approx=cv2.approxPolyDP(contours[0],epsilon,True)
adp=cv2.drawContours(adp,[approx],0,(0,0,255),2)
cv2.imshow("result0.09",adp)
##====================epsilon=0.055*周长===========================###
adp=o.copy()
epsilon=0.055*cv2.arcLength(contours[0],True)
approx=cv2.approxPolyDP(contours[0],epsilon,True)
adp=cv2.drawContours(adp,[approx],0,(0,0,255),2)
cv2.imshow("result0.055",adp)
##====================epsilon=0.05*周长===========================###
adp=o.copy()
epsilon=0.05*cv2.arcLength(contours[0],True)
approx=cv2.approxPolyDP(contours[0],epsilon,True)
adp=cv2.drawContours(adp,[approx],0,(0,0,255),2)
cv2.imshow("result0.05",adp)
##====================epsilon=0.02*周长===========================###
adp=o.copy()
epsilon=0.02*cv2.arcLength(contours[0],True)
approx=cv2.approxPolyDP(contours[0],epsilon,True)
adp=cv2.drawContours(adp,[approx],0,(0,0,255),2)
cv2.imshow("result0.02",adp)
##=====================等待释放窗口==================================##
cv2.waitKey()
cv2.destroyAllWindows()

In [23]:
#12.5 凸包
#观察函数cv2.convexHull()内参数 returnPoints的使用情况
import cv2
o=cv2.imread("finger.png",-1)
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
hull=cv2.convexHull(contours[0])   #返回坐标值
print("returnPoints为默认值True时返回值hull的值：\n",hull)
hull2=cv2.convexHull(contours[0],returnPoints=False)   #返回索引值
print("returnPoints为False时返回值hull的值：\n",hull2)

returnPoints为默认值True时返回值hull的值：
 [[[418 175]]

 [[313 401]]

 [[309 401]]

 [[246 400]]

 [[155 394]]

 [[108 269]]

 [[104 254]]

 [[102 244]]

 [[ 99 227]]

 [[ 98 221]]

 [[ 98 168]]

 [[128  75]]

 [[214  21]]

 [[313  69]]

 [[416 164]]

 [[417 165]]

 [[418 167]]]
returnPoints为False时返回值hull的值：
 [[415]
 [330]
 [329]
 [327]
 [315]
 [283]
 [275]
 [271]
 [265]
 [263]
 [262]
 [150]
 [  0]
 [528]
 [419]
 [418]
 [416]]


In [24]:
#使用函数 cv2.convexHull()获取轮廓的凸包
import cv2
o=cv2.imread("finger.png",-1)
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
hull=cv2.convexHull(contours[0])   #返回坐标值
cv2.polylines(o,[hull],True,(0,255,0),2)
cv2.imshow("result",o)
cv2.waitKey()
cv2.destroyAllWindows()

In [25]:
#12.5.2 凸缺陷
#使用函数 cv2.convexityDefects()计算凸缺陷
import cv2
import numpy as np
#=========================原图=========================================###
img=cv2.imread("finger.png",-1)
cv2.imshow("original",img)
#=========================构造轮廓=====================================###
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
#==========================凸包=======================================###
cnt=contours[0]
hull=cv2.convexHull(cnt,returnPoints=False)
defects=cv2.convexityDefects(cnt,hull)
print("defects=\n",defects)
#=========================构造凸缺陷==================================###
for i in range(defects.shape[0]):
    s,e,f,d=defects[i,0]
    start=tuple(cnt[s][0])
    end=tuple(cnt[e][0])
    far=tuple(cnt[f][0])
    cv2.line(img,start,end,[0,0,255],2)
    cv2.circle(img,far,5,[255,0,0],-1)
#====================显示结果，释放图像================================###
cv2.imshow("result",img)  
cv2.waitKey()
cv2.destroyAllWindows()

defects=
 [[[  416   418   417   114]]

 [[  419   528   468 33682]]

 [[  528     0   585 41624]]

 [[    0   150    74 44934]]

 [[  150   262   207 21825]]

 [[  263   265   264   210]]

 [[  265   271   270   445]]

 [[  271   275   274   251]]

 [[  275   283   278   231]]

 [[  283   315   314  6577]]

 [[  315   327   316   977]]

 [[  327   329   328   252]]

 [[  330   415   367 12416]]]


In [26]:
#12.5.3 几何学测试
#使用函数 cv2.isContourConvex()来判断轮廓是否是凸形的
import cv2
o=cv2.imread("finger.png",-1)
cv2.imshow("original",o)
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
#=============================凸包====================================###
image1=o.copy()
hull=cv2.convexHull(contours[0])
cv2.polylines(image1,[hull],True,(0,255,0),2)
print("使用函数cv2.convexHull()构造的多边形是否是凸形的:",cv2.isContourConvex(hull))
cv2.imshow("result1",image1)
#==========================逼近多边形================================####
image2=o.copy()
epsilon=0.01*cv2.arcLength(contours[0],True)
approx=cv2.approxPolyDP(contours[0],epsilon,True)
image2=cv2.drawContours(image2,[approx],0,(0,0,225),2)
print("使用函数cv2.approxPolyDP()构造的多边形是否是凸形的:",cv2.isContourConvex(approx))
cv2.imshow("result2",image2)
#==========================释放窗口===================================### 
cv2.waitKey()
cv2.destroyAllWindows()

使用函数cv2.convexHull()构造的多边形是否是凸形的: True
使用函数cv2.approxPolyDP()构造的多边形是否是凸形的: False


In [27]:
#使用函数 cv2.pointPolygonTest()计算点到轮廓的最短距离，需要将参数measureDist的值设置为True
import cv2
o=cv2.imread("finger.png",-1)
cv2.imshow("original",o)
#==========================获取凸包================================###
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
hull=cv2.convexHull(contours[0])
image=cv2.cvtColor(image,cv2.COLOR_GRAY2BGR)
cv2.polylines(image,[hull],True,(0,255,0),2)
print(hull)  #测试边缘到底在哪里，然后再使用确定的位置点绘制文字
#=======================内部点A到轮廓的距离==========================###
distA=cv2.pointPolygonTest(hull,(300,150),True)
font=cv2.FONT_HERSHEY_SIMPLEX
cv2.putText(image,"A",(300,150),font,1,(0,255,0),3)
print("disA=",distA)
#=======================外部点B到轮廓的距离==========================###
distB=cv2.pointPolygonTest(hull,(50,166),True)
font=cv2.FONT_HERSHEY_SIMPLEX
cv2.putText(image,"B",(50,166),font,1,(0,255,0),3)
print("disB=",distB)
#==================正好处于轮廓上的点C到轮廓的距离======================###
distC=cv2.pointPolygonTest(hull,(417,165),True)
font=cv2.FONT_HERSHEY_SIMPLEX
cv2.putText(image,"C",(417,165),font,1,(0,255,0),3)
print("disC=",distC)
#=================================显示=============================###
cv2.imshow("result1",image)
cv2.waitKey()
cv2.destroyAllWindows()

[[[418 175]]

 [[313 401]]

 [[309 401]]

 [[246 400]]

 [[155 394]]

 [[108 269]]

 [[104 254]]

 [[102 244]]

 [[ 99 227]]

 [[ 98 221]]

 [[ 98 168]]

 [[128  75]]

 [[214  21]]

 [[313  69]]

 [[416 164]]

 [[417 165]]

 [[418 167]]]
disA= 68.35502388271934
disB= -48.041648597857254
disC= -0.0


In [28]:
#12.6 利用形状场景算法比较轮廓
#12.6.1 计算形状场景距离
#使用cv2.createShapeContextDistanceExtractor() 计算形状场景距离
import cv2
#===========================原始图像o1的边缘=======================###
o1=cv2.imread("contours6_down.jpg",-1)
cv2.imshow("original1",o1)
gray1=cv2.cvtColor(o1,cv2.COLOR_BGR2GRAY)
ret,binary1=cv2.threshold(gray1,127,255,cv2.THRESH_BINARY)
image,contours1,hierarchy=cv2.findContours(binary1,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
cnt1=contours1[0]
#===========================原始图像o2的边缘=======================###
o2=cv2.imread("contours6x.jpg",-1)
cv2.imshow("original2",o2)
gray2=cv2.cvtColor(o2,cv2.COLOR_BGR2GRAY)
ret,binary2=cv2.threshold(gray2,127,255,cv2.THRESH_BINARY)
image,contours2,hierarchy=cv2.findContours(binary2,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
cnt2=contours2[0]
#===========================原始图像o3的边缘=======================###
o3=cv2.imread("finger.png",-1)
cv2.imshow("origina3",o3)
gray3=cv2.cvtColor(o3,cv2.COLOR_BGR2GRAY)
ret,binary3=cv2.threshold(gray3,127,255,cv2.THRESH_BINARY)
image,contours3,hierarchy=cv2.findContours(binary3,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
cnt3=contours3[0]
#=========================构建距离提取算子=========================###
sd=cv2.createShapeContextDistanceExtractor()
#==========================计算距离================================###
d1=sd.computeDistance(cnt1,cnt1)
print("与自身的距离d1=",d1)
d2=sd.computeDistance(cnt2,cnt1)
print("与旋转后的自身图像的距离d2=",d2)
d3=sd.computeDistance(cnt2,cnt3)
print("与不相似对象的距离d3=",d3)
cv2.waitKey()
cv2.destroyAllWindows()

与自身的距离d1= 0.0
与旋转后的自身图像的距离d2= 0.15000000596046448
与不相似对象的距离d3= 0.1996988207101822


In [29]:
#12.6.2 计算 Hausdorff距离
#使用函数cv2.createHausdorffDistanceExtractor()计算不同图像的Hausdorff距离
import cv2
#=========================读取原始图像====================================###
o1=cv2.imread("contours6_down.jpg",-1)
o2=cv2.imread("contours6x.jpg",-1)
o3=cv2.imread("finger.png",-1)
cv2.imshow("original1",o1)
cv2.imshow("original2",o2)
cv2.imshow("original3",o3)
#=========================色彩转换========================================###
gray1=cv2.cvtColor(o1,cv2.COLOR_BGR2GRAY)
gray2=cv2.cvtColor(o2,cv2.COLOR_BGR2GRAY)
gray3=cv2.cvtColor(o3,cv2.COLOR_BGR2GRAY)
#=========================阈值处理========================================###
ret,binary1=cv2.threshold(gray1,127,255,cv2.THRESH_BINARY)
ret,binary2=cv2.threshold(gray2,127,255,cv2.THRESH_BINARY)
ret,binary3=cv2.threshold(gray3,127,255,cv2.THRESH_BINARY)
#=========================提取轮廓========================================###
image,contours1,hierarchy=cv2.findContours(binary1,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
image,contours2,hierarchy=cv2.findContours(binary2,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
image,contours3,hierarchy=cv2.findContours(binary3,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
cnt1=contours1[0]
cnt2=contours2[0]
cnt3=contours3[0]
#=====================构造距离提取算子===================================###
hd=cv2.createHausdorffDistanceExtractor()
#=========================计算距离=======================================###
d1=hd.computeDistance(cnt1,cnt1)
print("与自身的Hausdorff距离d1=",d1)
d2=hd.computeDistance(cnt2,cnt1)
print("与旋转后的自身图像的Hausdorff距离d2=",d2)
d3=hd.computeDistance(cnt2,cnt3)
print("与不相似对象的Hausdorff距离d3=",d3)
cv2.waitKey()
cv2.destroyAllWindows()

与自身的Hausdorff距离d1= 0.0
与旋转后的自身图像的Hausdorff距离d2= 98.97979736328125
与不相似对象的Hausdorff距离d3= 191.230224609375


In [30]:
#12.7 轮廓的特征值
#12.7.1 宽高比 AspectRation
import cv2
o=cv2.imread("finger.png",-1)
cv2.imshow("original",o)
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
x,y,w,h=cv2.boundingRect(contours[0])
cv2.rectangle(o,(x,y),(x+w,y+h),(255,255,255),3)
aspectRatio=float(w)/h
print(aspectRatio)
cv2.imshow("result",o)  
cv2.waitKey()
cv2.destroyAllWindows()

0.84251968503937


In [31]:
#12.7.2 Extent
#计算图像的轮廓面积与其矩形边界面积之比
import cv2
o=cv2.imread("finger.png",-1)
cv2.imshow("original",o)
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
x,y,w,h=cv2.boundingRect(contours[0])
cv2.drawContours(o,contours[0],-1,(0,0,255),3)
cv2.rectangle(o,(x,y),(x+w,y+h),(255,255,255),3)
rectArea=w*h
cntArea=cv2.contourArea(contours[0])
extend=float(cntArea)/rectArea
print(extend)
cv2.imshow("result",o)
cv2.waitKey()
cv2.destroyAllWindows()

0.40083891382736037


In [32]:
#12.7.3 Solidity
#计算图像轮廓面积与凸包面积之比
import cv2
o=cv2.imread("finger.png",-1)
cv2.imshow("original",o)
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
cv2.drawContours(o,contours[0],-1,(0,0,255),3)
cntArea=cv2.contourArea(contours[0])
hull=cv2.convexHull(contours[0])
hullArea=cv2.contourArea(hull)
cv2.polylines(o,[hull],True,(0,255,0),2)
solidity=float(cntArea)/hullArea
print(solidity)
cv2.imshow("result",o)
cv2.waitKey()
cv2.destroyAllWindows()

0.5654357868269136


In [33]:
#12.7.4 等效直径（Equivalent Diameter）
#计算与轮廓面积相等的圆形的直径，并绘制与该轮廓等面积的圆
import cv2
import numpy as np
o=cv2.imread("finger.png",-1)
cv2.imshow("original",o)
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
cv2.drawContours(o,contours[0],-1,(0,0,255),3)
cntArea=cv2.contourArea(contours[0])
equiDiameter=np.sqrt(4*cntArea/np.pi)
print(equiDiameter)
cv2.circle(o,(200,200),int(equiDiameter/2),(0,0,255),3)
cv2.imshow("result",o)
cv2.waitKey()
cv2.destroyAllWindows()

249.83599060494043


In [34]:
#12.7.6 掩模和像素点
#使用OpenCV函数cv2.findNonZero()获取一个图像内的轮廓点的位置
import cv2
import numpy as np
#===========================读取原始图像=================================###
o=cv2.imread("finger.png",-1)
cv2.imshow("original",o)
#===========================获取轮廓=====================================###
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
cnt=contours[0]
#===========================绘制空心轮廓=================================###
mask1=np.zeros(gray.shape,np.uint8)
cv2.drawContours(mask1,[cnt],0,255,2)
pixelpoints1=cv2.findNonZero(mask1)
print("pixelpoints1.shape=",pixelpoints1.shape)
print("pixelpoints1=\n",pixelpoints1)
cv2.imshow("mask1",mask1)
#===========================绘制实心轮廓=================================###
mask2=np.zeros(gray.shape,np.uint8)
cv2.drawContours(mask2,[cnt],0,255,-1)
pixelpoints2=cv2.findNonZero(mask2)
print("pixelpoints2.shape=",pixelpoints2.shape)
print("pixelpoints2=\n",pixelpoints2)
cv2.imshow("mask2",mask2)
cv2.waitKey()
cv2.destroyAllWindows()

pixelpoints1.shape= (6929, 1, 2)
pixelpoints1=
 [[[214  20]]

 [[213  21]]

 [[214  21]]

 ...

 [[311 402]]

 [[312 402]]

 [[313 402]]]
pixelpoints2.shape= (50016, 1, 2)
pixelpoints2=
 [[[214  21]]

 [[214  22]]

 [[213  23]]

 ...

 [[311 401]]

 [[312 401]]

 [[313 401]]]


In [35]:
#12.7.7 最大值和最小值及它们的位置
#使用函数 cv2.minMaxLoc() 在图像内查找掩模指定区域内的最大值、最小值及其位置
import cv2
import numpy as np
o=cv2.imread("finger.png",-1)
cv2.imshow("original",o)
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
cnt=contours[0]
#=======================使用掩模获取感兴趣区域的最值====================###
mask=np.zeros(gray.shape,np.uint8)
mask=cv2.drawContours(mask,[cnt],-1,255,-1)
minVal,maxVal,minLoc,maxLoc=cv2.minMaxLoc(gray,mask=mask)
print("minVal=",minVal)
print("maxVal=",maxVal)
print("minLoc=",minLoc)
print("maxLoc=",maxLoc)
#=======================使用掩模获取感兴趣区域并显示=====================###
masko=np.zeros(o.shape,np.uint8)
masko=cv2.drawContours(masko,[cnt],-1,(255,255,255),-1)
loc=cv2.bitwise_and(o,masko)
cv2.imshow("mask",loc)
#显示灰度结果
#loc=cv2.bitwise_and(gray,masko)
#cv2.imshow("mask",loc)
cv2.waitKey()
cv2.destroyAllWindows()

minVal= 255.0
maxVal= 255.0
minLoc= (214, 21)
maxLoc= (214, 21)


In [36]:
#12.7.8 平均颜色及平均灰度
#使用函数cv2.mean()计算一个对象的平均灰度
import cv2
import numpy as np
o=cv2.imread("finger.png",-1)
cv2.imshow("original",o)
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
cnt=contours[0]
#=======================使用掩模获取感兴趣区域的均值===================###
mask=np.zeros(gray.shape,np.uint8) #构建mean所使用的掩模（必须是单通道的）
cv2.drawContours(mask,[cnt],0,(255,255,255),-1)
meanVal=cv2.mean(o,mask=mask)
print("meanVal=\n",meanVal)
#=======================使用掩模获取感兴趣区域并显示=====================###
masko=np.zeros(o.shape,np.uint8)
masko=cv2.drawContours(masko,[cnt],-1,(255,255,255),-1)
loc=cv2.bitwise_and(o,masko)
cv2.imshow("mask",loc)
cv2.waitKey()
cv2.destroyAllWindows()

meanVal=
 (255.0, 255.0, 255.0, 0.0)


In [37]:
#12.7.9 极点
#计算一副图像内的极值点
import cv2
import numpy as np
o=cv2.imread("finger.png",-1)
cv2.imshow("original",o)
#======================获取并绘制轮廓============================###
gray=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
image,contours,hierarchy=cv2.findContours(binary,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
cnt=contours[0]
mask=np.zeros(gray.shape,np.uint8)
cv2.drawContours(mask,[cnt],0,(255,255,255),-1)
#======================计算极值======================================###
leftmost=tuple(cnt[cnt[:,:,0].argmin()][0])
rightmost=tuple(cnt[cnt[:,:,0].argmax()][0])
topmost=tuple(cnt[cnt[:,:,1].argmin()][0])
bottommost=tuple(cnt[cnt[:,:,1].argmax()][0])
#======================打印极值=======================================###
print("leftmost=",leftmost)
print("rightmost=",rightmost)
print("topmost=",topmost)
print("bottommost=",bottommost)
#====================绘制文字说明====================================###
font=cv2.FONT_HERSHEY_COMPLEX
cv2.putText(o,"A",leftmost,font,1,(0,0,255),2)
cv2.putText(o,"B",rightmost,font,1,(0,0,255),2)
cv2.putText(o,"C",topmost,font,1,(0,0,255),2)
cv2.putText(o,"D",bottommost,font,1,(0,0,255),2)
#==================绘制图像=======================================###
cv2.imshow("result",o)
cv2.waitKey()
cv2.destroyAllWindows()

leftmost= (98, 168)
rightmost= (418, 175)
topmost= (214, 21)
bottommost= (309, 401)
