In [1]:
#23.1 Haar级联分类器
#使用函数cv2.CascadeClassifier.detectMultiScale()检测一幅图像内的人脸
import cv2
image=cv2.imread("face_recognize.jpg",-1)
#获取XML文件，加载人脸检测器
faceCascade=cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
print(faceCascade)
#色彩转换，转换成灰度图像
gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
#调用函数detectMultiScale
faces=faceCascade.detectMultiScale(gray,scaleFactor=1.15,minNeighbors=5,minSize=(5,5))
print(faces)
#打印输出的测试结果
print("发现{0}个人脸！".format(len(faces)))
#逐个标注人脸
for(x,y,w,h) in faces:
    #cv2.rectangle(image,(x,y),(x+w,y+w),(0,255,0),2)   #矩形标注
    cv2.circle(image,(int((x+x+w)/2),int((y+y+h)/2)),int(w/2),(0,255,0),2)
#显示结果
cv2.imshow("dect",image)
cv2.imwrite("re_1.jpg",image)
cv2.waitKey()
cv2.destroyAllWindows()

<CascadeClassifier 0000028B69731550>
[[225  97  46  46]
 [146 104  47  47]
 [ 91 111  52  52]
 [300 118  48  48]]
发现4个人脸！


In [2]:
#23.2 LBPH人脸识别
#利用LBPH完成一个简单的人脸识别程序
import cv2
import numpy as np
images=[]
images.append(cv2.imread("X1.jpg",0))
images.append(cv2.imread("X2.jpg",0))
images.append(cv2.imread("W1.jpg",0))
images.append(cv2.imread("W2.jpg",0))
labels=[0,0,1,1]
recognizer=cv2.face.LBPHFaceRecognizer_create()
recognizer.train(images,np.array(labels))
predict_image=cv2.imread("X3.jpg",0)
label,confidence=recognizer.predict(predict_image)
print("label",label)
print("confidence",confidence)

label 0
confidence 31.66312392941947


In [5]:
#23.3 EigenFaces人脸识别
#利用EigenFaces模块完成一个简单的人脸识别程序(图像大小必须相等)
import cv2
import numpy as np
import cv2
import numpy as np
images=[]
images.append(cv2.imread("Y1.jpg",0))
images.append(cv2.imread("Y2.jpg",0))
images.append(cv2.imread("Z1.jpg",0))
images.append(cv2.imread("Z2.jpg",0))
labels=[0,0,1,1]
recognizer=cv2.face.EigenFaceRecognizer_create()
recognizer.train(images,np.array(labels))
predict_image=cv2.imread("Z3.jpg",0)
label,confidence=recognizer.predict(predict_image)
print("label",label)
print("confidence",confidence)

label 1
confidence 25717.205371622666


In [7]:
#23.4 Fisherfaces人脸识别(图像大小必须相等)
import cv2
import numpy as np
import cv2
import numpy as np
images=[]
images.append(cv2.imread("Y1.jpg",0))
images.append(cv2.imread("Y3.jpg",0))
images.append(cv2.imread("Z1.jpg",0))
images.append(cv2.imread("Z2.jpg",0))
labels=[0,0,1,1]
recognizer=cv2.face.FisherFaceRecognizer_create()
recognizer.train(images,np.array(labels))
predict_image=cv2.imread("Y2.jpg",0)
label,confidence=recognizer.predict(predict_image)
print("label",label)
print("confidence",confidence)

label 0
confidence 21882.996563683926
