In [1]:
#3.1图像加法运算
import cv2
a=cv2.imread("lena.png",0)
b=a
result1=a+b
result2=cv2.add(a,b)
cv2.imshow("original",a)
cv2.imshow("result1",result1)
cv2.imshow("result2",result2)
cv2.waitKey()
cv2.destroyAllWindows()

In [2]:
#3.2图像加权和
import cv2
import numpy as np
img1=np.ones((3,4),dtype=np.uint8)*100##生成一个3*4大小的、元素值都是100的二维数组
img2=np.ones((3,4),dtype=np.uint8)*10
gamma=3
img3=cv2.addWeighted(img1,0.6,img2,5,gamma)  ###计算img1*0.6+img2*5+3
print(img3)

[[113 113 113 113]
 [113 113 113 113]
 [113 113 113 113]]


In [3]:
import cv2
import numpy as np
img1=np.random.randint(10,100,size=[3,4],dtype=np.uint8)
img2=np.random.randint(20,200,size=[3,4],dtype=np.uint8)
gamma=3
img3=cv2.addWeighted(img1,0.6,img2,5,gamma)  ###计算img1*0.6+img2*5+3
print(img1)
print(img2)
print(img3)

[[88 86 24 90]
 [93 56 34 57]
 [17 35 78 21]]
[[151 181 172 175]
 [139 194 177  90]
 [145 155  86 165]]
[[255 255 255 255]
 [255 255 255 255]
 [255 255 255 255]]


In [4]:
#3.3 按位逻辑运算
#3.3.1 按位与运算
import cv2
import numpy as np
a=np.random.randint(0,255,[5,5],dtype=np.uint8)
b=np.zeros((5,5),dtype=np.uint8)
b[0:3,0:3]=255
b[4,4]=255
c=cv2.bitwise_and(a,b)
print("a=\n",a)
print("b=\n",b)
print("c=\n",c)

a=
 [[ 39 218 103  51 248]
 [ 33 222  76  40 141]
 [234 112 125 103 109]
 [ 19  44 204  32 188]
 [221 180 113   1 171]]
b=
 [[255 255 255   0   0]
 [255 255 255   0   0]
 [255 255 255   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0 255]]
c=
 [[ 39 218 103   0   0]
 [ 33 222  76   0   0]
 [234 112 125   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0 171]]


In [5]:
import cv2
import numpy as np
a=cv2.imread("lena.png",0)
b=np.zeros(a.shape,dtype=np.uint8)
b[50:245,45:245]=255
b[50:290,45:130]=255
c=cv2.bitwise_and(a,b)
cv2.imshow("a",a)
cv2.imshow("b",b)
cv2.imshow("c",c)
cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
#3.4 掩模
import cv2
import numpy as np
img1=np.ones((4,4),dtype=np.uint8)*3
img2=np.ones((4,4),dtype=np.uint8)*5
img3=np.ones((4,4),dtype=np.uint8)*66
mask=np.ones((4,4),dtype=np.uint8)
mask[:,0:2]=0
mask[0:2,:]=0
print("img1=\n",img1)
print("img2=\n",img2)
print("mask=\n",mask)
print("初始值img3=\n",img3)
img3=cv2.add(img1,img2,mask=mask)
print("求和后img3=\n",img3)

img1=
 [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
img2=
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
mask=
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 1 1]
 [0 0 1 1]]
初始值img3=
 [[66 66 66 66]
 [66 66 66 66]
 [66 66 66 66]
 [66 66 66 66]]
求和后img3=
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 8 8]
 [0 0 8 8]]


In [7]:
#3.6 位平面分解
import cv2
import numpy as np
lena=cv2.imread("lena.png",0)
cv2.imshow("lena",lena)
r,c=lena.shape
x=np.zeros((r,c,8),dtype=np.uint8)
for i in range(0,8):
    x[:,:,i]=2**i
r=np.zeros((r,c,8),dtype=np.uint8)
for i in range(0,8):
    r[:,:,i]=cv2.bitwise_and(lena,x[:,:,i])
    mask=r[:,:,i]>0
    r[mask]=255
    cv2.imshow(str(i),r[:,:,i])
cv2.waitKey()
cv2.destroyAllWindows()

In [8]:
#3.7 图像加密和解密
import cv2
import numpy as np
lena=cv2.imread("lena.png",0)
key=np.random.randint(0,256,lena.shape,dtype=np.uint8)
encryption=cv2.bitwise_xor(lena,key)
decryption=cv2.bitwise_xor(encryption,key)
cv2.imshow("lena",lena)
cv2.imshow("key",key)
cv2.imshow("encryption",encryption)
cv2.imshow("decryption",decryption)
cv2.waitKey()
cv2.destroyAllWindows()