In [1]:
#5.1 缩放
#cv2.resize的行列属性与shape相反 
import cv2
import numpy as np
img=np.ones([2,4,3],dtype=np.uint8)
size=img.shape[:2]
rst=cv2.resize(img,size)
print("img.shape=",img.shape)
print("img=\n",img)
print("rst.shape=",rst.shape)
print("rst=\n",rst)

img.shape= (2, 4, 3)
img=
 [[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
rst.shape= (4, 2, 3)
rst=
 [[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [2]:
#完成一个简单的图形缩放
import cv2
import numpy as np
img=cv2.imread("lena.png",-1)
rows,cols=img.shape[:2]
size=(int(cols*0.9),int(rows*0.5))
rst=cv2.resize(img,size)
print("img.shape=",img.shape)
print("rst.shape=",rst.shape)

img.shape= (300, 300, 3)
rst.shape= (150, 270, 3)


In [3]:
#根据函数cv2.resize()的fx参数、fy参数完成图形缩放
import cv2
img=cv2.imread("lena.png",-1)
rst=cv2.resize(img,None,fx=2,fy=0.5)
print("img.shape=",img.shape)
print("rst.shape=",rst.shape)

img.shape= (300, 300, 3)
rst.shape= (150, 600, 3)


In [4]:
#5.2 翻转
import cv2
img=cv2.imread("lena.png",-1)
x=cv2.flip(img,0)
y=cv2.flip(img,1)
xy=cv2.flip(img,-1)
cv2.imwrite("lenax.png",x)
cv2.imwrite("lenay.png",y)
cv2.imshow("img",img)
cv2.imshow("x",x)
cv2.imshow("y",y)
cv2.imshow("xy",xy)
cv2.waitKey()
cv2.destroyAllWindows()

In [5]:
#5.3 仿射
#5.3.1 平移
#平移转换矩阵M=np.float32([[1,0,x],[0,1,y]])
import cv2
import numpy as np
img=cv2.imread("lena.png",-1)
height,width=img.shape[:2]
x=50
y=100
M=np.float32([[1,0,x],[0,1,y]])
move=cv2.warpAffine(img,M,(width,height))
cv2.imshow("original",img)
cv2.imshow("move",move)
cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
#5.3.2 旋转
#旋转转换矩阵M=cv2.getRotationMatrix2D(center,angle,scale)
import cv2
img=cv2.imread("lena.png",-1)
height,width=img.shape[:2]
M=cv2.getRotationMatrix2D((width/2,height/2),45,0.6)
rotate=cv2.warpAffine(img,M,(width,height))
cv2.imshow("original",img)
cv2.imshow("rotate",rotate)
cv2.waitKey()
cv2.destroyAllWindows()

In [7]:
#5.3.3 更复杂的仿射变换
#转换矩阵M=cv2.getAffineTransform(输入图像的三个点坐标，输出图像的三个点坐标)
#三个点分别为左上角、右上角、左下角
import cv2
import numpy as np
img=cv2.imread("lena.png",-1)
rows,cols,ch=img.shape
p1=np.float32([[0,0],[cols-1,0],[0,rows-1]])
p2=np.float32([[0,rows*0.33],[cols*0.85,rows*0.25],[cols*0.15,rows*0.7]])
M=cv2.getAffineTransform(p1,p2)
dst=cv2.warpAffine(img,M,(cols,rows))
cv2.imshow("original",img)
cv2.imshow("dst",dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [8]:
#5.5 重映射
#5.5.1 映射参数的理解
import cv2
import numpy as np
img=np.random.randint(0,256,[4,5],dtype=np.uint8)
rows,cols=img.shape
mapx=np.ones(img.shape,np.float32)*3
mapy=np.zeros(img.shape,np.float32)
rst=cv2.remap(img,mapx,mapy,cv2.INTER_LINEAR)
print("img=\n",img)
print("mapx=\n",mapx)
print("mapy=\n",mapy)
print("rst=\n",rst)

img=
 [[  7 148  67  11 138]
 [201 232 211 125 148]
 [190   2 218 181 223]
 [ 60 232 125  80  80]]
mapx=
 [[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
mapy=
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
rst=
 [[11 11 11 11 11]
 [11 11 11 11 11]
 [11 11 11 11 11]
 [11 11 11 11 11]]


In [9]:
#5.5.2 复制
import cv2
import numpy as np
img=np.random.randint(0,256,size=[4,5],dtype=np.uint8)
rows,cols=img.shape
mapx=np.zeros(img.shape,np.float32)
mapy=np.zeros(img.shape,np.float32)
for i in range(rows):
    for j in range(cols):
        mapx.itemset((i,j),j)
        mapy.itemset((i,j),i)
rst=cv2.remap(img,mapx,mapy,cv2.INTER_LINEAR)
print("img=\n",img)
print("mapx=\n",mapx)
print("mapy=\n",mapy)
print("rst=\n",rst)

img=
 [[250 173 131  48 225]
 [194 147  12  37  71]
 [141 131 240 186  47]
 [244  15 185   7  42]]
mapx=
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
mapy=
 [[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]]
rst=
 [[250 173 131  48 225]
 [194 147  12  37  71]
 [141 131 240 186  47]
 [244  15 185   7  42]]


In [10]:
#图像复制
import cv2
import numpy as np
img=cv2.imread("lena.png",-1)
rows,cols=img.shape[:2]
mapx=np.zeros(img.shape[:2],np.float32)
mapy=np.zeros(img.shape[:2],np.float32)
for i in range(rows):
    for j in range(cols):
        mapx.itemset((i,j),j)
        mapy.itemset((i,j),i)
rst=cv2.remap(img,mapx,mapy,cv2.INTER_LINEAR)
cv2.imshow("original",img)
cv2.imshow("remap",rst)
cv2.waitKey()
cv2.destroyAllWindows()

In [11]:
#5.5.3 绕X轴翻转
#绕X轴翻转时，map2中当前行的行号调整为“总行数-1-当前行号”
import cv2
import numpy as np
img=np.random.randint(0,256,size=[4,5],dtype=np.uint8)
rows,cols=img.shape
mapx=np.zeros(img.shape,np.float32)
mapy=np.zeros(img.shape,np.float32)
for i in range(rows):
    for j in range(cols):
        mapx.itemset((i,j),j)
        mapy.itemset((i,j),rows-1-i)
rst=cv2.remap(img,mapx,mapy,cv2.INTER_LINEAR)
print("img=\n",img)
print("mapx=\n",mapx)
print("mapy=\n",mapy)
print("rst=\n",rst)

img=
 [[142  69 232  22 148]
 [  8  89   6 187 138]
 [177 124 191   2 185]
 [ 60 223 100  13 191]]
mapx=
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
mapy=
 [[3. 3. 3. 3. 3.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]
rst=
 [[ 60 223 100  13 191]
 [177 124 191   2 185]
 [  8  89   6 187 138]
 [142  69 232  22 148]]


In [12]:
#图像绕X轴翻转
import cv2
import numpy as np
img=cv2.imread("lena.png",-1)
rows,cols=img.shape[:2]
mapx=np.zeros(img.shape[:2],np.float32)
mapy=np.zeros(img.shape[:2],np.float32)
for i in range(rows):
    for j in range(cols):
        mapx.itemset((i,j),j)
        mapy.itemset((i,j),rows-1-i)
rst=cv2.remap(img,mapx,mapy,cv2.INTER_LINEAR)
cv2.imshow("original",img)
cv2.imshow("result",rst)
cv2.waitKey()
cv2.destroyAllWindows()

In [13]:
#5.5.4 绕Y轴翻转
#绕Y轴翻转时，map1中当前行的行号调整为“总列数-1-当前列号”
import cv2
import numpy as np
img=np.random.randint(0,256,size=[4,5],dtype=np.uint8)
rows,cols=img.shape
mapx=np.zeros(img.shape,np.float32)
mapy=np.zeros(img.shape,np.float32)
for i in range(rows):
    for j in range(cols):
        mapx.itemset((i,j),cols-1-j)
        mapy.itemset((i,j),i)
rst=cv2.remap(img,mapx,mapy,cv2.INTER_LINEAR)
print("img=\n",img)
print("mapx=\n",mapx)
print("mapy=\n",mapy)
print("rst=\n",rst)

img=
 [[  6  71 222 195   0]
 [ 10 182 186 116  35]
 [142  86  10  57  99]
 [148 171  80  27  85]]
mapx=
 [[4. 3. 2. 1. 0.]
 [4. 3. 2. 1. 0.]
 [4. 3. 2. 1. 0.]
 [4. 3. 2. 1. 0.]]
mapy=
 [[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]]
rst=
 [[  0 195 222  71   6]
 [ 35 116 186 182  10]
 [ 99  57  10  86 142]
 [ 85  27  80 171 148]]


In [14]:
#图像绕Y轴翻转
import cv2
import numpy as np
img=cv2.imread("lena.png",-1)
rows,cols=img.shape[:2]
mapx=np.zeros(img.shape[:2],np.float32)
mapy=np.zeros(img.shape[:2],np.float32)
for i in range(rows):
    for j in range(cols):
        mapx.itemset((i,j),cols-1-j)
        mapy.itemset((i,j),i)
rst=cv2.remap(img,mapx,mapy,cv2.INTER_LINEAR)
cv2.imshow("original",img)
cv2.imshow("result",rst)
cv2.waitKey()
cv2.destroyAllWindows()

In [15]:
#5.5.5 绕X轴、Y轴翻转
#绕Y轴翻转时，map1中当前行的行号调整为“总列数-1-当前列号”
#绕X轴翻转时，map2中当前行的行号调整为“总行数-1-当前行号”
import cv2
import numpy as np
img=np.random.randint(0,256,size=[4,5],dtype=np.uint8)
rows,cols=img.shape
mapx=np.zeros(img.shape,np.float32)
mapy=np.zeros(img.shape,np.float32)
for i in range(rows):
    for j in range(cols):
        mapx.itemset((i,j),cols-1-j)
        mapy.itemset((i,j),rows-1-i)
rst=cv2.remap(img,mapx,mapy,cv2.INTER_LINEAR)
print("img=\n",img)
print("mapx=\n",mapx)
print("mapy=\n",mapy)
print("rst=\n",rst)

img=
 [[133  79  90  92  86]
 [210  67 230 180 181]
 [225 223 193 233 210]
 [195 223  14 162 221]]
mapx=
 [[4. 3. 2. 1. 0.]
 [4. 3. 2. 1. 0.]
 [4. 3. 2. 1. 0.]
 [4. 3. 2. 1. 0.]]
mapy=
 [[3. 3. 3. 3. 3.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]
rst=
 [[221 162  14 223 195]
 [210 233 193 223 225]
 [181 180 230  67 210]
 [ 86  92  90  79 133]]


In [16]:
#图像绕X轴、Y轴翻转
import cv2
import numpy as np
img=cv2.imread("lena.png",-1)
rows,cols=img.shape[:2]
mapx=np.zeros(img.shape[:2],np.float32)
mapy=np.zeros(img.shape[:2],np.float32)
for i in range(rows):
    for j in range(cols):
        mapx.itemset((i,j),cols-1-j)
        mapy.itemset((i,j),rows-1-i)
rst=cv2.remap(img,mapx,mapy,cv2.INTER_LINEAR)
cv2.imshow("original",img)
cv2.imshow("result",rst)
cv2.waitKey()
cv2.destroyAllWindows()

In [17]:
#5.5.6 X轴、Y轴互换
import cv2
import numpy as np
img=np.random.randint(0,256,size=[4,5],dtype=np.uint8)
rows,cols=img.shape
mapx=np.zeros(img.shape,np.float32)
mapy=np.zeros(img.shape,np.float32)
for i in range(rows):
    for j in range(cols):
        mapx.itemset((i,j),i)
        mapy.itemset((i,j),j)
rst=cv2.remap(img,mapx,mapy,cv2.INTER_LINEAR)
print("img=\n",img)
print("mapx=\n",mapx)
print("mapy=\n",mapy)
print("rst=\n",rst)

img=
 [[232 135 105 149 130]
 [123 239 225 254  87]
 [155   5  66 248 227]
 [ 83 117  47  60 140]]
mapx=
 [[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]]
mapy=
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
rst=
 [[232 123 155  83   0]
 [135 239   5 117   0]
 [105 225  66  47   0]
 [149 254 248  60   0]]


In [18]:
#图像X轴、Y轴互换
import cv2
import numpy as np
img=cv2.imread("lena.png",-1)
rows,cols=img.shape[:2]
mapx=np.zeros(img.shape[:2],np.float32)
mapy=np.zeros(img.shape[:2],np.float32)
for i in range(rows):
    for j in range(cols):
        mapx.itemset((i,j),i)
        mapy.itemset((i,j),j)
rst=cv2.remap(img,mapx,mapy,cv2.INTER_LINEAR)
cv2.imshow("original",img)
cv2.imshow("result",rst)
cv2.waitKey()
cv2.destroyAllWindows()

In [19]:
#5.5.7 图像缩放
import cv2
import numpy as np
img=cv2.imread("lena.png",-1)
rows,cols=img.shape[:2]
mapx=np.zeros(img.shape[:2],np.float32)
mapy=np.zeros(img.shape[:2],np.float32)
for i in range(rows):
    for j in range(cols):
        if 0.25*cols<i<0.75*cols and 0.25*rows<j<0.75*rows:
            mapx.itemset((i,j),2*(j-cols*0.25)+0.5)
            mapy.itemset((i,j),2*(i-rows*0.25)+0.5)
        else:
            mapx.itemset((i,j),0)
            mapy.itemset((i,j),0)
rst=cv2.remap(img,mapx,mapy,cv2.INTER_LINEAR)
cv2.imshow("original",img)
cv2.imshow("result",rst)
cv2.waitKey()
cv2.destroyAllWindows()