In [1]:
#6.1 threshold函数
#6.1.1 二值化阈值处理(cv2.THRESH_BINARY)
import cv2
import numpy as np
img=np.random.randint(0,256,[4,5],dtype=np.uint8)
t,rst=cv2.threshold(img,127,256,cv2.THRESH_BINARY)
print("img=\n",img)
print("t=",t)
print("rst=\n",rst)

img=
 [[131  26  99 215 106]
 [217  32 194  41 167]
 [241 210  27 176 114]
 [243 246 126 146 222]]
t= 127.0
rst=
 [[255   0   0 255   0]
 [255   0 255   0 255]
 [255 255   0 255   0]
 [255 255   0 255 255]]


In [2]:
#处理图像
import cv2
import numpy as np
img=cv2.imread("lena.png",0)
t,rst=cv2.threshold(img,100,256,cv2.THRESH_BINARY)
cv2.imshow("img",img)
cv2.imshow("rst",rst)
cv2.waitKey()
cv2.destroyAllWindows()

In [3]:
#6.1.2 反二值化阈值处理(cv2.THRESH_BINARY_INV)
import cv2
import numpy as np
img=cv2.imread("lena.png",0)
t,rst=cv2.threshold(img,100,256,cv2.THRESH_BINARY_INV)
cv2.imshow("img",img)
cv2.imshow("rst",rst)
cv2.waitKey()
cv2.destroyAllWindows()

In [4]:
#6.1.3 截断阈值化处理(cv2.THRESH_TRUNC)
import cv2
import numpy as np
img=cv2.imread("lena.png",0)
r,rst=cv2.threshold(img,100,256,cv2.THRESH_TRUNC)
cv2.imshow("img",img)
cv2.imshow("rst",rst)
cv2.waitKey()
cv2.destroyAllWindows()

In [5]:
#6.1.4 超阈值零处理(cv2.THRESH_TOZERO_INV)
import cv2
import numpy as np
img=cv2.imread("lena.png",0)
t,rst=cv2.threshold(img,100,256,cv2.THRESH_TOZERO_INV)
cv2.imshow("img",img)
cv2.imshow("rst",rst)
cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
#6.1.4 低阈值零处理(cv2.THRESH_TOZERO)
import cv2
import numpy as np
img=cv2.imread("lena.png",0)
t,rst=cv2.threshold(img,100,256,cv2.THRESH_TOZERO)
cv2.imshow("img",img)
cv2.imshow("rst",rst)
cv2.waitKey()
cv2.destroyAllWindows()

In [7]:
#6.2 自适应阈值处理
#cv2.adaptiveThreshold()
#分别使用cv2.Threshold()和 cv2.adaptiveThreshold()处理图像
import cv2
import numpy as np
img=cv2.imread("lena.png",0)
t,thd=cv2.threshold(img,100,255,cv2.THRESH_BINARY)
athdMEAN=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_MEAN_C,cv2.THRESH_BINARY,5,3)
athdGAUS=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY,5,3)
cv2.imshow("img",img)
cv2.imshow("thd",thd)
cv2.imshow("athdMEAN",athdMEAN)
cv2.imshow("athdGAUS",athdGAUS)
cv2.waitKey()
cv2.destroyAllWindows()

In [8]:
#Otsu处理
import cv2
import numpy as np
img=cv2.imread("lena.png",0)
t1,thd=cv2.threshold(img,100,255,cv2.THRESH_BINARY)
t2,otsu=cv2.threshold(img,0,255,cv2.THRESH_BINARY+cv2.THRESH_OTSU)
print("t1=",t1)
print("t2=",t2)
cv2.imshow("thd",thd)
cv2.imshow("otsu",otsu)
cv2.waitKey()
cv2.destroyAllWindows()

t1= 100.0
t2= 93.0
