In [1]:
#8.1 腐蚀
import cv2
import numpy as np
o=cv2.imread("lena.png",-1)
kernel=np.ones((5,5),np.uint8)
r1=cv2.erode(o,kernel)
r2=cv2.erode(o,kernel,iterations=5)
cv2.imshow("original",o)
cv2.imshow("result1",r1)
cv2.imshow("result2",r2)
cv2.waitKey()
cv2.destroyAllWindows()

In [2]:
#8.2 膨胀
import cv2
import numpy as np
o=cv2.imread("lena.png",-1)
kernel1=np.ones((9,9),np.uint8)
kernel2=np.ones((5,5),np.uint8)
r1=cv2.dilate(o,kernel1)
r2=cv2.dilate(o,kernel2)
r3=cv2.dilate(o,kernel2,iterations=9)
cv2.imshow("original",o)
cv2.imshow("result1",r1)
cv2.imshow("result2",r2)
cv2.imshow("result3",r3)
cv2.waitKey()
cv2.destroyAllWindows()

In [3]:
#8.4 开运算
#开运算先腐蚀再膨胀，可以去噪，cv2.morphologyEx() op=cv.MORPH_OPEN
import cv2
import numpy as np
o=cv2.imread("lena.png",-1)
k=np.ones((5,5),np.uint8)
r=cv2.morphologyEx(o,cv2.MORPH_OPEN,k)
cv2.imshow("original",o)
cv2.imshow("result1",r)
cv2.waitKey()
cv2.destroyAllWindows()

In [4]:
#8.5 闭运算
#闭运算先膨胀后腐蚀，有助于关闭前景物体内部小孔，cv2.morphologyEx() op=cv.MORPH_CLOSE
import cv2
import numpy as np
o=cv2.imread("lena.png",-1)
k=np.ones((5,5),np.uint8)
r=cv2.morphologyEx(o,cv2.MORPH_CLOSE,k)
cv2.imshow("original",o)
cv2.imshow("result1",r)
cv2.waitKey()
cv2.destroyAllWindows()

In [5]:
#8.6 形态学梯度运算
#用膨胀图像减去腐蚀图像, cv2.morphologyEx() op=cv.MORPH_GRADIENT
import cv2
import numpy as np
o=cv2.imread("lena.png",-1)
k=np.ones((5,5),np.float32)
r=cv2.morphologyEx(o,cv2.MORPH_GRADIENT,k)
cv2.imshow("original",o)
cv2.imshow("result1",r)
cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
#8.7 礼帽运算
#原始图像减去开运算，cv2.morphologyEx() op=cv.MORPH_TOPHAT
import cv2
import numpy as np
o=cv2.imread("lena.png",-1)
k=np.ones((5,5),np.float32)
r=cv2.morphologyEx(o,cv2.MORPH_TOPHAT,k)
cv2.imshow("original",o)
cv2.imshow("result1",r)
cv2.waitKey()
cv2.destroyAllWindows()

In [7]:
#8.8 黑帽运算
#闭运算减去原始图像，可以获取图像内部小孔，cv2.morphologyEx() op=cv.MORPH_BLACKHAT
import cv2
import numpy as np
o=cv2.imread("lena.png",-1)
k=np.ones((5,5),np.float32)
r=cv2.morphologyEx(o,cv2.MORPH_BLACKHAT,k)
cv2.imshow("original",o)
cv2.imshow("result1",r)
cv2.waitKey()
cv2.destroyAllWindows()

In [8]:
# 8.9 核函数
import cv2
kernel1=cv2.getStructuringElement(cv2.MORPH_RECT,(5,5))
kernel2=cv2.getStructuringElement(cv2.MORPH_CROSS,(5,5))
kernel3=cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))
print("kernel1=\n",kernel1)
print("kernel2=\n",kernel2)
print("kernel3=\n",kernel3)
#处理图像
import cv2
o=cv2.imread("lena.png",-1)
kernel1=cv2.getStructuringElement(cv2.MORPH_RECT,(15,15))
kernel2=cv2.getStructuringElement(cv2.MORPH_CROSS,(15,15))
kernel3=cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(15,15))
dst1=cv2.dilate(o,kernel1)
dst2=cv2.dilate(o,kernel2)
dst3=cv2.dilate(o,kernel3)
cv2.imshow("original",o)
cv2.imshow("result1",dst1)
cv2.imshow("result2",dst2)
cv2.imshow("result3",dst3)
cv2.waitKey()
cv2.destroyAllWindows()

kernel1=
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
kernel2=
 [[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]
kernel3=
 [[0 0 1 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 1 0 0]]
